hideManual: true
watch:
  directories:
    - src
    - tests
    - templates
    - config
  fileMask:
    - '*.php'
    - '*.twig'
    - '*.yaml'
notifications:
  passingTests: false
  failingTests: false
phpunit:
  binaryPath: vendor/bin/pest
  arguments: '--stop-on-failure --colors=always'
  timeout: 180
