controllers:
  resource: ../../src/Controller/
  type: annotation

account:
  resource: ../../src/Domain/Account/Controller/
  type: annotation

tweet:
  resource: ../../src/Domain/Tweet/Controller/
  type: annotation

following:
  resource: ../../src/Domain/Following/Controller/
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
